#source components/common.sh
#
#CHECK_ROOT
#
#PRINT " Install YUM repos"
#curl -L https://raw.githubusercontent.com/roboshop-devops-project/redis/main/redis.repo -o /etc/yum.repos.d/redis.repo &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Install redis"
#yum install redis-6.2.7 -y &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Update redis configuration"
#sed -i -e 's/127.0.0.1/0.0.0.0/'  /etc/redis.conf  /etc/redis/redis.conf &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Start redis service"
#systemctl enable redis &>>${LOG} && systemctl restart redis &>>${LOG}
#CHECK_STAT $?

#- name: Copy {{COMPONENT}} yum repos
#  ansible.builtin.template:
#    src: redis.repo
#    dest: /etc/yum.repos.d/redis.repo

- name: Install redis rpm
  ansible.builtin.command:
    - dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    - dnf module enable redis:remi-6.2 -y

- name: Install {{COMPONENT}}
  ansible.builtin.yum:
    name:
      - redis
    state: installed

- name: Update {{COMPONENT}} configuration
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    enabled: yes
    state: restarted

