- name: Fail if the RABBITMQ_USER_PASSWORD variable is not declared
  ansible.builtin.fail:
    msg: Need RABBITMQ_USER_PASSWORD variable
  when: RABBITMQ_USER_PASSWORD is undefined

- name: Import a role
  ansible.builtin.include_role:
    name: common
    tasks_from: python

