#
#    PRINT "Install nginx"
#    yum install nginx -y &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Download ${COMPONENT} content"
#    curl -s -L -o /tmp/${COMPONENT}.zip "https://github.com/roboshop-devops-project/${COMPONENT}/archive/main.zip" &>>${LOG}
#    CHECK_STAT $?
#
#    cd /usr/share/nginx/html
#
#    PRINT "Remove old content"
#    rm -rf * &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Organize ${COMPONENT} content"
#    unzip /tmp/${COMPONENT}.zip &>>${LOG} && mv ${COMPONENT}-main/static/* . &>>${LOG} && mv ${COMPONENT}-main/localhost.conf /etc/nginx/default.d/roboshop.conf &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Setup systemd configuration"
#    sed -i -e '/catalogue/  s/localhost/catalogue.roboshop.internal/' -e '/user/  s/localhost/user.roboshop.internal/' -e '/cart/  s/localhost/cart.roboshop.internal/' -e '/shipping/  s/localhost/shipping.roboshop.internal/' -e '/payment/  s/localhost/payment.roboshop.internal/' /etc/nginx/default.d/roboshop.conf &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Start nginx service"
#    systemctl enable nginx &>>${LOG} && systemctl restart nginx &>>${LOG}
#    CHECK_STAT $?
#  }
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed