#
#
#
#
#    PRINT "Organize ${COMPONENT} content"
#    unzip /tmp/${COMPONENT}.zip &>>${LOG} && mv ${COMPONENT}-main/static/* . &>>${LOG} && mv ${COMPONENT}-main/localhost.conf /etc/nginx/default.d/roboshop.conf &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Setup systemd configuration"
#    sed -i -e '/catalogue/  s/localhost/catalogue.roboshop.internal/' -e '/user/  s/localhost/user.roboshop.internal/' -e '/cart/  s/localhost/cart.roboshop.internal/' -e '/shipping/  s/localhost/shipping.roboshop.internal/' -e '/payment/  s/localhost/payment.roboshop.internal/' /etc/nginx/default.d/roboshop.conf &>>${LOG}
#    CHECK_STAT $?
#
#    PRINT "Start nginx service"
#    systemctl enable nginx &>>${LOG} && systemctl restart nginx &>>${LOG}
#    CHECK_STAT $?
#  }
- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Import content
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Remove the directory path
  ansible.builtin.file:
    path: /tmp/{{COMPONENT}}.zip
    state: absent

- name: Move the content to the app location
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main{{SUFFIX}}/
    dest: "{{APP_LOCATION}}"
    remote_src: yes

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes

