- name: Copy repo for filebeat installation
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/

- name: Install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed
    enabled: yes
