- name: Copy logstash configuration
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: Wait for port 5044 to become open on the host, don't start checking for 10 seconds
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 5044
    delay: 30
    timeout: 60
