- name: Prometheus server setup
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: server
  when: SET_TYPE == "server"

- name: Prometheus server setup
  ansible.builtin.include_role:
    name: prometheus
    tasks_from: client
  when: SET_TYPE == "client"