- name: prometheus server configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: prometheus alerts configuration
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: Restart prometheus server
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Wait for port 9090 to become open on the host, don't start checking for 10 seconds
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9090
    delay: 10
    timeout: 15

- name: prometheus alertmanager configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart alertmanager server
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: Wait for port 9093 to become open on the host, don't start checking for 10 seconds
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9093
    delay: 10
    timeout: 15