- name: Install golang
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Import a role for {{COMPONENT}} content
  ansible.builtin.include_role:
    name: common
    tasks_from: download

#This set is done by CI as standard practice
#- name: Install golang dependencies
#  ansible.builtin.shell:
#    - go mod init dispatch
#    - go get
#    - go build

- name: Import a role for {{COMPONENT}} content
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd