- name: Install maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: Import a role for {{COMPONENT}} content
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install maven dependencies
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/roboshop/{{COMPONENT}}

- name: Setup {{COMPONENT}} systemd configuration
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    daemon_reload: yes
    state:  restarted
    enabled: yes