#PRINT "Setting up NodeJS repository"
#curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Install NodeJS"
#yum install nodejs -y &>>${LOG}
##CHECK_STAT $?
#
#APP_COMMON_SETUP
#
#mv ${COMPONENT}-main ${COMPONENT}
#cd ${COMPONENT}
#
#PRINT "Install NodeJS dependencies"
#npm install &>>${LOG}
#CHECK_STAT $?
#
#SYSTEMD
#}

- name: Setup nodejs repository
  ansible.builtin.shell:  curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Import a role for {{COMPONENT}} content
  ansible.builtin.include_role:
    name: common
    tasks_from: download

#This set is done by CI as standard practice
#- name: Install packages based on package.json.
#  community.general.npm:
#    path: "{{APP_LOCATION}}"

- name: Download public key for docdb access
  ansible.builtin.get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: /home/roboshop/catalogue/rds-combined-ca-bundle.pem
    mode: '0400'
    owner: roboshop
  when: DOCDB_ENDPOINT != "null"
#above 0400 -meaning given the owner only read permisssions

- name: Import a role for {{COMPONENT}} content
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

- name: Install filebeat
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat






