#PRINT "Setting up NodeJS repository"
#curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash &>>${LOG}
#CHECK_STAT $?
#
#PRINT "Install NodeJS"
#yum install nodejs -y &>>${LOG}
##CHECK_STAT $?
#
#APP_COMMON_SETUP
#
#mv ${COMPONENT}-main ${COMPONENT}
#cd ${COMPONENT}
#
#PRINT "Install NodeJS dependencies"
#npm install &>>${LOG}
#CHECK_STAT $?
#
#SYSTEMD
#}

- name: Setup nodejs repository
  ansible.builtin.shell:  curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Import a role for {{COMPONENT}} content
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install packages based on package.json.
  community.general.npm:
    path: "{{APP_LOCATION}}"

- name: Setting up {{COMPONENT}} SystemD configuration
  ansible.built.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    daemon_reload: yes
    state:  restarted

